healthcarenotes/urls.py
from django.urls import path
from healthcarenotes import views

urlpatterns = [
    path("<uuid:healthcare_id>/notes/", views.show_all_healthcare_notes, name="show_all_healthcare_notes"),
    path("<uuid:healthcare_id>/notes/<uuid:note_id>", views.show_healthcare_note, name="show_healthcare_note"),
    path("<uuid:healthcare_id>/notes/<uuid:note_id>/download", views.download_healthcare_note, name="download_healthcare_note"),
    path("<uuid:healthcare_id>/notes/<uuid:note_id>/edit-permission/<uuid:perm_id>", views.edit_healthcare_note_permission, name="edit_healthcare_note_permission"),
    path("<uuid:healthcare_id>/notes/new", views.create_healthcare_note, name="create_healthcare_note"),
    path("<uuid:healthcare_id>/patients/<uuid:patient_id>/notes/new", views.create_healthcare_note_for_patient, name="create_healthcare_note_for_patient"),
    path("<uuid:healthcare_id>/notes/<uuid:note_id>/edit", views.edit_healthcare_note, name="edit_healthcare_note"),
]

userlogs/urls.py
from django.urls import path
from userlogs import views

urlpatterns = [
]

healthcarenotes/forms.py
from django import forms
from django_bleach.models import BleachField

from core.models import Patient
from patientrecords.models import Readings, TimeSeries, Documents, Images, Videos, DocumentsPerm

##########################################
################# Fields #################
##########################################

class PatientModelChoiceField(forms.ModelChoiceField):
  """
  Get full name of Healthcare objects in the ModelChoiceField
  """
  def label_from_instance(self, obj):
    return obj.username.get_full_name()

class ReadingsMultipleChoiceField(forms.ModelMultipleChoiceField):

  def label_from_instance(self, obj):
    datetime = obj.timestamp.strftime("%a, %d %b %Y %I:%M %p")
    
    return datetime + " " + obj.type

class TimeSeriesMultipleChoiceField(forms.ModelMultipleChoiceField):

  def label_from_instance(self, obj):
    datetime = obj.timestamp.strftime("%a, %d %b %Y %I:%M %p")
    
    return datetime

class ImgVidMultipleChoiceField(forms.ModelMultipleChoiceField):

  def label_from_instance(self, obj):
    datetime = obj.timestamp.strftime("%a, %d %b %Y %I:%M %p")
    
    return datetime + " Type: " + obj.type + " Title: " + obj.title

class DocumentsPermissionEditForm(forms.ModelForm):
  class Meta:
    model = DocumentsPerm
    fields = ['perm_value']

class AddHealthcareNote(forms.Form):
  patient = PatientModelChoiceField(queryset=Patient.objects.all())
  
  def __init__(self,*args,**kwargs):
    self.healthcare = kwargs.pop('healthcare')
    super(AddHealthcareNote, self).__init__(*args,**kwargs)
    self.fields['patient'].queryset = Patient.objects.filter(healthcare_patients=self.healthcare)

class AddHealthcareNoteForPatient(forms.Form):
  title = forms.CharField(max_length=64, required=True)
  note = forms.CharField(widget=forms.Textarea(attrs={"rows":5, "cols":20}), required=True)
  attach_readings = ReadingsMultipleChoiceField(queryset=Readings.objects.all(), required=False)
  attach_timeseries = TimeSeriesMultipleChoiceField(queryset=TimeSeries.objects.all(), required=False)
  attach_images = ImgVidMultipleChoiceField(queryset=Images.objects.all(), required=False)
  attach_videos = ImgVidMultipleChoiceField(queryset=Videos.objects.all(), required=False)

  def __init__(self,*args,**kwargs):
    self.patient = kwargs.pop('patient')
    super(AddHealthcareNoteForPatient, self).__init__(*args,**kwargs)
    self.fields['attach_readings'].queryset = Readings.objects.filter(patient_id=self.patient)
    self.fields['attach_timeseries'].queryset = TimeSeries.objects.filter(patient_id=self.patient)
    self.fields['attach_images'].queryset = Images.objects.filter(patient_id=self.patient)
    self.fields['attach_videos'].queryset = Videos.objects.filter(patient_id=self.patient)

class EditHealthcareNote(forms.Form):
  title = forms.CharField(max_length=64, required=True)
  note = forms.CharField(widget=forms.Textarea(attrs={"rows":5, "cols":20}), required=True)
  attach_readings = ReadingsMultipleChoiceField(queryset=Readings.objects.all(), required=False)
  attach_timeseries = TimeSeriesMultipleChoiceField(queryset=TimeSeries.objects.all(), required=False)
  attach_images = ImgVidMultipleChoiceField(queryset=Images.objects.all(), required=False)
  attach_videos = ImgVidMultipleChoiceField(queryset=Videos.objects.all(), required=False)

  def __init__(self,*args,**kwargs):
    self.patient = kwargs.pop('patient')
    super(EditHealthcareNote, self).__init__(*args,**kwargs)
    self.fields['attach_readings'].queryset = Readings.objects.filter(patient_id=self.patient)
    self.fields['attach_timeseries'].queryset = TimeSeries.objects.filter(patient_id=self.patient)
    self.fields['attach_images'].queryset = Images.objects.filter(patient_id=self.patient)
    self.fields['attach_videos'].queryset = Videos.objects.filter(patient_id=self.patient)

    

healthcarenotes/views.py
from __future__ import division, unicode_literals

import codecs
import os
from mimetypes import guess_type
import random
import string

import bleach
from bs4 import BeautifulSoup
from django.conf import settings
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponse
from django.shortcuts import render, redirect

from core.models import Healthcare
from healthcarenotes.forms import DocumentsPermissionEditForm, AddHealthcareNote, AddHealthcareNoteForPatient, \
  EditHealthcareNote
from patientrecords.models import Documents, DocumentsPerm
from userlogs.models import Logs


@login_required(login_url='/healthcare/login/')
@user_passes_test(lambda u: u.is_healthcare(), login_url='/healthcare/login/')
@user_passes_test(lambda u: u.pass_2fa(), login_url='/healthcare/login/')
def show_all_healthcare_notes(request, healthcare_id):
  """
  List all healthcare notes the healthcare professional has written for his patients
  """ 
  # checks if logged in healthcare professional has the same id as in the URL
  if (request.user.healthcare_username.id != healthcare_id):
    Logs.objects.create(type='READ', user_id=request.user.uid, interface='HEALTHCARE', status=STATUS_ERROR, details='[Show All Notes] Logged in user does not match ID in URL. URL ID: ' + str(healthcare_id))
    return redirect('/healthcare/login/')

  healthcare = healthcare_does_not_exists(healthcare_id)

  notes = Documents.objects.filter(owner_id_id=healthcare.username, type='Healthcare Professional Note')

  Logs.objects.create(type='READ', user_id=healthcare.username.uid, interface='HEALTHCARE', status=STATUS_OK, details='[Show All Notes]')

  context = {
    'healthcare': healthcare,
    'notes': notes,
  }

  return render(request, 'show_all_healthcare_notes.html', context)

@login_required(login_url='/healthcare/login/')
@user_passes_test(lambda u: u.is_healthcare(), login_url='/healthcare/login/')
@user_passes_test(lambda u: u.pass_2fa(), login_url='/healthcare/login/')
def show_healthcare_note(request, healthcare_id, note_id):
  """
  Show information of a single healthcare professional note
  """
  # checks if logged in healthcare professional has the same id as in the URL
  if (request.user.healthcare_username.id != healthcare_id):
    Logs.objects.create(type='READ', user_id=request.user.uid, interface='HEALTHCARE', status=STATUS_ERROR, details='[Show Note] Logged in user does not match ID in URL. URL ID: ' + str(healthcare_id))
    return redirect('/healthcare/login/')

  healthcare = healthcare_does_not_exists(healthcare_id)

  try:
    note = Documents.objects.filter(id=note_id)
    note = note[0]
  except IndexError:
    Logs.objects.create(type='READ', interface='HEALTHCARE', status=STATUS_ERROR, details='[Show Note] Note ID is invalid. Invalid ID: ' + str(note_id))
    return redirect('show_all_healthcare_notes', healthcare_id=healthcare_id)

  # Checks if healthcare has permission to view note
  if not note.is_owner_healthcare_note(healthcare.username):
    Logs.objects.create(type='READ', user_id=healthcare.username.uid, interface='HEALTHCARE', status=STATUS_ERROR, details='[Show Note] Permission Denied.')
    return redirect('show_all_healthcare_notes', healthcare_id=healthcare_id)

  # Path to view restricted record
  note_path = os.path.join(settings.PROTECTED_MEDIA_PATH, str(note_id))

  permissions = DocumentsPerm.objects.filter(docs_id=note_id)

  Logs.objects.create(type='READ', user_id=healthcare.username.uid, interface='HEALTHCARE', status=STATUS_OK, details='[Show Note] Show Note ' + str(note_id))

  context = {
    'healthcare': healthcare,
    'note': note,
    'permissions': permissions,
    'note_path': note_path,
  }

  return render(request, 'show_healthcare_note.html', context)

@login_required(login_url='/healthcare/login/')
@user_passes_test(lambda u: u.is_healthcare(), login_url='/healthcare/login/')
@user_passes_test(lambda u: u.pass_2fa(), login_url='/healthcare/login/')
def download_healthcare_note(request, healthcare_id, note_id):
  """
  Downloads a single healthcare professional note
  """
  # checks if logged in healthcare professional has the same id as in the URL
  if (request.user.healthcare_username.id != healthcare_id):
    Logs.objects.create(type='READ', user_id=request.user.uid, interface='HEALTHCARE', status=STATUS_ERROR, details='[Download Note] Logged in user does not match ID in URL. URL ID: ' + str(healthcare_id))
    return redirect('/healthcare/login/')

  healthcare = healthcare_does_not_exists(healthcare_id)

  try:
    note = Documents.objects.filter(id=note_id)
    note = note[0]
  except IndexError:
    Logs.objects.create(type='READ', interface='HEALTHCARE', status=STATUS_ERROR, details='[Download Note] Note ID is invalid. Invalid ID: ' + str(note_id))
    return redirect('show_all_healthcare_notes', healthcare_id=healthcare_id)

  # Checks if healthcare has permission to download note
  if not note.is_owner_healthcare_note(healthcare.username):
    Logs.objects.create(type='READ', user_id=healthcare.username.uid, interface='HEALTHCARE', status=STATUS_ERROR, details='[Download Note] Permission Denied.')
    return redirect('show_all_healthcare_notes', healthcare_id=healthcare_id)

  try:
    file_path = note.data.path
  except ValueError:
    Logs.objects.create(type='READ', user_id=healthcare.username.uid, interface='PATIENT', status=STATUS_ERROR, details='[Download Notes] No data path in note ' + str(note_id))
    return redirect('show_healthcare_note', healthcare_id=healthcare_id, note_id=note_id)

  file_path = note.data.path # E.g. /home/sadm/Desktop/.../x.html
  file_name = note.data.name.split('/', 1)[1] # x.html

  with open(file_path, 'rb') as note:
    content_type = guess_type(file_path)[0]
    response = HttpResponse(note, content_type=content_type)
    response['Content-Length'] = os.path.getsize(file_path)
    response['Content-Disposition'] = "attachment; filename=%s" %  file_name

    Logs.objects.create(type='READ', user_id=healthcare.username.uid, interface='HEALTHCARE', status=STATUS_OK, details='[Download Note] Download Note ' + str(note_id))

    return response

@login_required(login_url='/healthcare/login/')
@user_passes_test(lambda u: u.is_healthcare(), login_url='/healthcare/login/')
@user_passes_test(lambda u: u.pass_2fa(), login_url='/healthcare/login/')
def edit_healthcare_note_permission(request, healthcare_id, note_id, perm_id):
  """
  Edit a permission of a single healthcare_professional_note
  """
  # checks if logged in healthcare professional has the same id as in the URL
  if (request.user.healthcare_username.id != healthcare_id):
    Logs.objects.create(type='READ', user_id=request.user.uid, interface='HEALTHCARE', status=STATUS_ERROR, details='[Edit Note Permission] Logged in user does not match ID in URL. URL ID: ' + str(healthcare_id))
    return redirect('/healthcare/login/')

  healthcare = healthcare_does_not_exists(healthcare_id)

  try:
    note = Documents.objects.filter(id=note_id)
    note = note[0]
  except IndexError:
    Logs.objects.create(type='READ', user_id=healthcare.username.uid, interface='HEALTHCARE', status=STATUS_ERROR, details='[Edit Note Permission] Note ID is invalid. Invalid ID: ' + str(note_id))
    return redirect('show_all_healthcare_notes', healthcare_id=healthcare_id)

  try:
    permission = DocumentsPerm.objects.filter(id = perm_id)
    permission = permission[0]
  except IndexError:
    Logs.objects.create(type='READ', user_id=healthcare.username.uid, interface='HEALTHCARE', status=STATUS_ERROR, details='[Edit Note Permission] Permission ID is invalid.')
    return redirect('show_healthcare_note', healthcare_id=healthcare_id, note_id=note_id)

  form = DocumentsPermissionEditForm(request.POST or None, instance=permission)

  if request.method == 'POST':
    if form.is_valid():
      permission.save()
      Logs.objects.create(type='UPDATE', user_id=healthcare.username.uid, interface='HEALTHCARE', status=STATUS_OK, details='[Edit Note Permission] Edit Note ' + str(note_id) + ' permission ' + str(perm_id))
      return redirect('show_healthcare_note', healthcare_id=healthcare_id, note_id=note_id)
    else:
      Logs.objects.create(type='UPDATE', user_id=healthcare.username.uid, interface='HEALTHCARE', status=STATUS_ERROR, details='[Edit Note Permission] Invalid Form')
      context = {
        'form': form,
        'healthcare': healthcare,
        'note': note,
        'permission': permission
      }
      return render(request, 'edit_healthcare_note_permission.html', context)

  Logs.objects.create(type='READ', user_id=healthcare.username.uid, interface='HEALTHCARE', status=STATUS_OK, details='[Edit Note Permission] Render Form for Note ' + str(note.id))

  context = {
    'form': form,
    'healthcare': healthcare,
    'note': note,
    'permission': permission
  }

  return render(request, 'edit_healthcare_note_permission.html', context)

@login_required(login_url='/healthcare/login/')
@user_passes_test(lambda u: u.is_healthcare(), login_url='/healthcare/login/')
@user_passes_test(lambda u: u.pass_2fa(), login_url='/healthcare/login/')
def create_healthcare_note(request, healthcare_id):
  """
  Create a new healthcare professional note
  """
  # checks if logged in healthcare professional has the same id as in the URL
  if (request.user.healthcare_username.id != healthcare_id):
    Logs.objects.create(type='READ', user_id=request.user.uid, interface='HEALTHCARE', status=STATUS_ERROR, details='[Create Note] Logged in user does not match ID in URL. URL ID: ' + str(healthcare_id))
    return redirect('/healthcare/login/')

  healthcare = healthcare_does_not_exists(healthcare_id)

  form = AddHealthcareNote(request.POST, healthcare=healthcare)

  if request.method == 'POST':
    if form.is_valid():
      note_patient = form.cleaned_data['patient']

healthcarenotes/templates/create_healthcare_note.html
{% extends "healthcare_base.html" %}

{% load widget_tweaks %}

{% block content %}
<h1>Create New Healthcare Professional Note</h1>

<form action="{% url 'create_healthcare_note' healthcare_id=healthcare.id %}" method="post">
  {% csrf_token %}

  {% for field in form.visible_fields %}
    <div class="form-group">
      {{ field.label_tag }}

      {% if form.is_bound %}
        {% if field.errors %}
          {% render_field field class="form-control is-invalid" %}
          {% for error in field.errors %}
            <div class="invalid-feedback">
              {{ error }}
            </div>
          {% endfor %}
        {% else %}
          {% render_field field class="form-control is-valid" %}
        {% endif %}
      {% else %}
        {% render_field field class="form-control" %}
      {% endif %}

      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
  {% endfor %}

  <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

healthcarenotes/templates/create_healthcare_note_for_patient.html
{% extends "healthcare_base.html" %}

{% load widget_tweaks %}

{% block content %}
<h1>Create New Healthcare Professional Note</h1>

<form action="{% url 'create_healthcare_note_for_patient' healthcare_id=healthcare.id patient_id=patient.id %}" method="post">
  {% csrf_token %}

  {% for field in form.visible_fields %}
    <div class="form-group">
      {{ field.label_tag }}

      {% if form.is_bound %}
        {% if field.errors %}
          {% render_field field class="form-control is-invalid" %}
          {% for error in field.errors %}
            <div class="invalid-feedback">
              {{ error }}
            </div>
          {% endfor %}
        {% else %}
          {% render_field field class="form-control is-valid" %}
        {% endif %}
      {% else %}
        {% render_field field class="form-control" %}
      {% endif %}

      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
  {% endfor %}

  <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

healthcarenotes/templates/edit_healthcare_note.html
{% extends "healthcare_base.html" %}

{% load widget_tweaks %}

{% block content %}
<h1>Edit Healthcare Professional Note</h1>

<form action="{% url 'edit_healthcare_note' healthcare_id=healthcare.id note_id=note.id %}" method="post">
  {% csrf_token %}

  {% for field in form.visible_fields %}
    <div class="form-group">
      {{ field.label_tag }}

      {% if field.label == "Note" or field.label == "Title" %}

        {% if form.is_bound %}
          {% if field.errors %}
            {% render_field field class="form-control is-invalid" value=field.initial placeholder=field.initial %}
            {% for error in field.errors %}
              <div class="invalid-feedback">
                {{ error }}
              </div>
            {% endfor %}
          {% else %}
            {% render_field field class="form-control is-valid" value=field.initial placeholder=field.initial %}
          {% endif %}
        {% else %}
          {% render_field field class="form-control" value=field.initial placeholder=field.initial %}
        {% endif %}

        {% if field.help_text %}
          <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}

      {% else %}

        {% if form.is_bound %}
          {% if field.errors %}
            {% render_field field class="form-control is-invalid" %}
            {% for error in field.errors %}
              <div class="invalid-feedback">
                {{ error }}
              </div>
            {% endfor %}
          {% else %}
            {% render_field field class="form-control is-valid" %}
          {% endif %}
        {% else %}
          {% render_field field class="form-control" %}
        {% endif %}

        {% if field.help_text %}
          <small class="form-text text-muted">{{ field.help_text }}</small>
        {% endif %}

      {% endif %}
    </div>
  {% endfor %}

  <button type="submit" class="btn btn-primary">Submit</button>
</form>

<script>
  note_initial = $("#id_note").attr("placeholder")
  $("#id_note").text(note_initial);

  {% for reading in saved_attached_readings %}
    $("#id_attach_readings option[value={{ reading.id }}]").prop('selected', true);
  {% endfor %}

  {% for timeseries in saved_attached_timeseries %}
    $("#id_attach_timeseries option[value={{ timeseries.id }}]").prop('selected', true);
  {% endfor %}

  {% for video in saved_attached_videos %}
    $("#id_attach_videos option[value={{ video.id }}]").prop('selected', true);
  {% endfor %}

  {% for image in saved_attached_images %}
    $("#id_attach_images option[value={{ image.id }}]").prop('selected', true);
  {% endfor %}
</script>

{% endblock %}

healthcarenotes/templates/edit_healthcare_note_permission.html
{% extends "healthcare_base.html" %}

{% load app_filters %}
{% load widget_tweaks %}

{% block content %}
<h1> Edit Permission </h1>

<div>
  <label>Note Title: {{ note.title }}</label>
</div>

<div>
  <label>Note Writen For: {{ note.patient_id | get_patient_full_name }}</label>
</div>

<div>
  {% for name in permission.username.all %}
     <label>Permission Given To: {{ name | get_full_name }}</label>
  {% endfor %}
</div>

<div>
  <label>Permission Given By: {{ permission.given_by | get_full_name }}</label>
</div>

<form action="{% url 'edit_healthcare_note_permission' healthcare_id=healthcare.id note_id=note.id perm_id=permission.id %}" method="post">
  {% csrf_token %}

  {% for field in form.visible_fields %}
    <div class="form-group">
      {{ field.label_tag }}

      {% if form.is_bound %}
        {% if field.errors %}
          {% render_field field class="form-control is-invalid" %}
          {% for error in field.errors %}
            <div class="invalid-feedback">
              {{ error }}
            </div>
          {% endfor %}
        {% else %}
          {% render_field field class="form-control is-valid" %}
        {% endif %}
      {% else %}
        {% render_field field class="form-control" %}
      {% endif %}

      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
  {% endfor %}

  <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

healthcarenotes/templates/show_all_healthcare_notes.html
{% extends "healthcare_base.html" %}

{% load app_filters %}

{% block content %}
<h1>Healthcare Professional Notes</h1>

<table class="table text-center">
  <thead>
  <tr>
    <th scope="col">Timestamp</th>
    <th scope="col">Title</th>
    <th scope="col">Written For</th>
    <th scope="col">Data</th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  {% for note in notes %}
  <tr>
    <th scope="row">{{ note.timestamp | get_datetime }}</th>
    <th>{{ note.title }}</th>
    <th>{{ note.patient_id | get_patient_full_name }}</th>
    <th>
      <a href="{{ note.id | get_record_path }}">View Note</a>
    </th>
    <th><a href="{% url 'show_healthcare_note' healthcare_id=healthcare.id note_id=note.id %}">More Details</a></th>
  </tr>
  {% endfor %}
  </tbody>
</table>

{% endblock %}

healthcarenotes/templates/show_healthcare_note.html
{% extends "healthcare_base.html" %}

{% load app_filters %}

{% block content %}
<h1>{{ note.title }}</h1>

<table class="table text-center">
  <tr>
    <th>Date</th>
    <th>{{ note.timestamp | get_date }}</th>
  </tr>
  <tr>
    <th>Time</th>
    <th>{{ note.timestamp | get_time }}</th>
  </tr>
  <tr>
    <th>Written For</th>
    <th>{{ note.patient_id | get_patient_full_name }}</th>
  </tr>
  <tr>
    <th>Note</th>
    <th><a href="{{ note_path }}">View Note</a> | <a href="{% url 'download_healthcare_note' healthcare_id=healthcare.id note_id=note.id %}">Download Note</a></th>
  </tr>
  <tr>
    <th>Edit</th>
    <th><a href="{% url 'edit_healthcare_note' healthcare_id=healthcare.id note_id=note.id %}">Edit Note</a></th>
  </tr>
</table>

<h1>Permissions</h1>

<table class="table text-center">
  <thead>
  <tr>
    <th scope="col">Given To</th>
    <th scope="col">Given By</th>
    <th scope="col">Given On</th>
    <th scope="col">Permission</th>
    <th scope="col"></th>
  </tr>
  </thead>
  <tbody>
  {% for perm in permissions %}
  {% to_model_name perm as to_model_name_result %}
  <tr>
    <th scope="row">
      {% for name in perm.username.all %}
        {{ name | get_full_name }}
      {% endfor %}
    </th>
    <th>{{ perm.given_by | get_full_name }}</th>
    <th>{{ perm.timestamp | get_datetime }}</th>
    <th>{{ perm.perm_value | get_perm }}</th>
    <th><a href="{% url 'edit_healthcare_note_permission' healthcare_id=healthcare.id note_id=note.id perm_id=perm.id %}">Edit Permission</a></th>
  </tr>
  {% endfor %}
  </tbody>
</table>

{% endblock %}